import type { Metadata } from "next";
import localFont from "next/font/local";
import Image from "next/image";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { FooterLogo } from "./assets";
import AuthProvider from "@/context/AuthProvider";
import RecoilRootWrapper from "@/context/RecoilRootWrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <RecoilRootWrapper>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            {children}
            {/*<footer className="bg-slate-900 lg:py-20 px-7 py-10 pb-0 lg:pb-0">
          <div className="container mx-auto">
            <div className="grid lg:grid-cols-5 grid-cols-1 gap-4">
              <div className="col-span-2 lg:pr-16 mb-6">
                <Image
                  src={FooterLogo} // Path to the image in the public directory
                  alt="Description of the image"
                  width={206} // Set width
                  height={60} // Set height
                />
                <p className="mt-5 text-[16px] text-white align-left text-opacity-70">
                  SalonX offers a luxurious and innovative salon experience,
                  blending cutting-edge techniques with personalized service to
                  bring out the best in every client
                </p>
              </div>
              <div>
                <h6 className="font-medium text-[#D78B30] uppercase mb-5">
                  Link
                </h6>
                <ul className="*:text-white *:pb-5 *:text-opacity-70 *:text-[16px]">
                  <li>Unisex Services</li>
                  <li>Women Services</li>
                  <li> Men Services</li>
                  <li> Our history</li>
                  <li> Contact</li>
                </ul>
              </div>
              <div>
                <h6 className="font-medium text-[#D78B30] uppercase mb-5">
                  About
                </h6>
                <ul className="*:text-white *:pb-5 *:text-opacity-70 *:text-[16px]">
                  <li>FAQ</li>
                  <li>Contact Us</li>
                  <li> Terms & Conditions</li>
                  <li>Privacy Policy </li>
                  <li> Term to Use</li>
                </ul>
              </div>
              <div>
                <h6 className="font-medium text-[#D78B30] uppercase mb-5">
                  Contact
                </h6>
                <ul className="*:text-white *:pb-5 *:text-opacity-70 *:text-[16px]">
                  <li>contact@salonx.com</li>
                  <li>+33 888 666 433</li>
                  <li> Empire State Building, New York</li>
                  <li> 9h00 -17h00</li>
                </ul>
              </div>
            </div>
            <hr className="mt-14 opacity-70" />
            <div className="text-center py-7">
              <p className="text-[16px] text-white text-opacity-70">
                © 2024 Salon X. All rights reserved.
              </p>
            </div>
          </div>
        </footer>*/}
          </body>
        </RecoilRootWrapper>
      </AuthProvider>
    </html>
  );
}
